[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/weather"
  to = "/.netlify/functions/weather"
  status = 200

  [[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200
